routes/web.php
<?php

use App\Http\Controllers\ConfigController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FileDownloadController;
use App\Http\Controllers\HumanResourceController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\JenisJenjangController;
use App\Http\Controllers\LayananController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MenuHyperlinkController;
use App\Http\Controllers\MenuStatisController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProfilInstansiController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\SarprasController;
use App\Http\Controllers\SDMController;
use App\Http\Controllers\Section4Controller;
use App\Http\Controllers\SlideshowController;
use App\Http\Controllers\SubMenuController;
use App\Http\Controllers\SubMenuHyperlinkController;
use App\Http\Controllers\TestimoniController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebsiteController;
use App\Models\HumanResource;
use App\Models\MenuDinamis;
use App\Models\Testimoni;
use Illuminate\Support\Facades\Route;
use Spatie\Analytics\AnalyticsFacade as Analytics;
use Spatie\Analytics\Period;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Login & Logout
Route::get('/login', [LoginController::class, 'index'])
    ->name('login')
    ->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::get('/sejarah', [ProfilInstansiController::class, 'sejarah']);
Route::get('/visi-misi', [ProfilInstansiController::class, 'visi_misi']);
Route::get('/tugas-fungsi', [ProfilInstansiController::class, 'tugas_fungsi']);
Route::get('/struktur-organisasi', [ProfilInstansiController::class, 'struktur_organisasi']);
Route::get('/sumber-daya-manusia', [ProfilInstansiController::class, 'sumber_daya_manusia']);
Route::get('/maklumat-layanan', [ProfilInstansiController::class, 'maklumat_layanan']);
Route::get('/faq-anri', [FaqController::class, 'website']);

Route::get('/', [Section4Controller::class, 'section']);

// Beranda Website
Route::get('/', [WebsiteController::class, 'website_beranda']);
Route::get('/kontak-kami', [WebsiteController::class, 'website_kontak']);

// Program Diklat
Route::get('/program-diklat-anri', [WebsiteController::class, 'program_diklat']);

// Detail Program Diklat
Route::get('/detail-program-diklat/{Program:kode_diklat}', [WebsiteController::class, 'program_detail']);

// Artikel
Route::get('/artikel', [WebsiteController::class, 'artikel']);

// Berita
Route::get('/berita', [WebsiteController::class, 'berita']);
Route::get('/berita-detail/{Publication:slug}', [WebsiteController::class, 'berita_detail']);

// Infografis
Route::get('/infografis', [WebsiteController::class, 'infografis']);
Route::get('/informasi-detail/{Publication:slug}', [WebsiteController::class, 'infografis_detail']);

// Pengumuman
Route::get('/pengumuman', [WebsiteController::class, 'pengumuman']);

// Sarana Prasarana Frontend
Route::get('/prasarana-sarana', [WebsiteController::class, 'website_sarpras']);

// Menu
Route::get('/ANRI/{Pages:nama_menu}', [WebsiteController::class, 'view_menu']);
Route::get('/sub-menu/{SubMenu:url}', [WebsiteController::class, 'view_submenu']);

// Calendar
Route::get('/kalender-diklat', [ProgramController::class, 'getEvent'])->name('getevent');
Route::get('/pencarian-kalender-diklat', [ProgramController::class, 'search_program'])->name('getevent_search');

// Search
Route::get('/hasil-pencarian', [WebsiteController::class, 'search']);
Route::get('/hasil-pencarian-berita-artikel', [WebsiteController::class, 'search_berita']);
Route::get('/hasil-pencarian-infografis-artikel', [WebsiteController::class, 'search_infografis']);
Route::get('/hasil-pencarian-artikel', [WebsiteController::class, 'search_artikel']);
Route::get('/hasil-pencarian-pengumuman', [WebsiteController::class, 'search_pengumuman']);
Route::get('/hasil-pencarian-program', [WebsiteController::class, 'search_program']);

Route::group(['middleware' => ['auth', 'role:admin', 'status']], function () {
    // dashboard
    Route::get('/dashboard', [WebsiteController::class, 'dashboard_counter']);
    Route::get('/dashboard-filter', [WebsiteController::class, 'dashboard_search']);

    // Approval admin
    Route::put('/approve-jenis/{Jenis:id}', [JenisJenjangController::class, 'approve_jenis'])->name('approve-jenis');
    Route::put('/unapprove-jenis/{Jenis:id}', [JenisJenjangController::class, 'unapprove_jenis'])->name('unapprove-jenis');
    Route::put('/approve-jenjang/{Jenjang:id}', [JenisJenjangController::class, 'approve_jenjang'])->name('approve-jenjang');
    Route::put('/unapprove-jenjang/{Jenjang:id}', [JenisJenjangController::class, 'unapprove_jenjang'])->name('unapprove-jenjang');
    
    // Approval program dan unapproval
    Route::put('/approve-program/{Program:id}', [ProgramController::class, 'approve_program'])->name('approve-program');
    Route::put('/approve-program/approve', [ProgramController::class, 'approve_program'])->name('approve-program-mass');
    Route::put('/unapprove-program/{Program:id}', [ProgramController::class, 'unapprove_program'])->name('unapprove-program');
    Route::put('/unapprove-program/unapprove', [ProgramController::class, 'unapprove_program'])->name('unapprove-program-mass');
   
    // Approval testimoni dan unapproval
    Route::put('/approve-testimoni/{Testimoni:id}', [TestimoniController::class, 'approve_testimoni'])->name('approve-testimoni');
    Route::put('/approve-testimoni/approve', [TestimoniController::class, 'approve_testimoni'])->name('approve-testimoni-mass');
    Route::put('/unapprove-testimoni/{Testimoni:id}', [TestimoniController::class, 'unapprove_testimoni'])->name('unapprove-testimoni');
    Route::put('/unapprove-testimoni/unapprove', [TestimoniController::class, 'unapprove_testimoni'])->name('unapprove-testimoni-mass');
    
    // Approval dan Unapproval FAQ
    Route::put('/approve-faq/{Faq:id}', [FaqController::class, 'approve_faq'])->name('approve-faq');
    // Route::put('/unapprove-faq/unapprove', [FaqController::class, 'unapprove_faq'])->name('unapprove-faq-mass');
    Route::put('/approve-faq/approve', [FaqController::class, 'approve_faq'])->name('approve-faq-mass');
    Route::put('/unapprove-faq/{Faq:id}', [FaqController::class, 'unapprove_faq'])->name('unapprove-faq');
    Route::put('/unapprove-faq/unapprove', [FaqController::class, 'unapprove_faq'])->name('unapprove-faq-mass');
    
    // Approval slideshow dan unapproval
    Route::put('/approve-slideshow/{Slideshow:id}', [SlideshowController::class, 'approve_slideshow'])->name('approve-slideshow');
    Route::put('/approve-slideshow/approve', [SlideshowController::class, 'approve_slideshow'])->name('approve-slideshow-mass');
    Route::put('/unapprove-slideshow/{Slideshow:id}', [SlideshowController::class, 'unapprove_slideshow'])->name('unapprove-slideshow');
    Route::put('/unapprove-slideshow/unapprove', [SlideshowController::class, 'unapprove_slideshow'])->name('unapprove-slideshow-mass');
    
    // Approve dan Unappproval publikasi
    Route::put('/approve-publikasi/{Publication:id}', [PublicationController::class, 'approve_publikasi'])->name('approve-publikasi');
    Route::put('/approve-publikasi/aprrove', [PublicationController::class, 'approve_publikasi'])->name('approve-publikasi-mass');
    Route::put('/unapprove-publikasi/{Publication:id}', [PublicationController::class, 'unapprove_publikasi'])->name('unapprove-publikasi');
    Route::put('/unapprove-publikasi/unapprove', [PublicationController::class, 'unapprove_publikasi'])->name('unapprove-publikasi-mass');
    
    // Approve dan Unapprove File Download
    Route::put('/approve-file/{FileDownload:id}', [FileDownloadController::class, 'approve_file'])->name('approve-file');
    Route::put('/approve-file/aprrove', [FileDownloadController::class, 'approve_file'])->name('approve-file-mass');
    Route::put('/unapprove-file/{FileDownload:id}', [FileDownloadController::class, 'unapprove_file'])->name('unapprove-file');
    Route::put('/unapprove-file/unapprove', [FileDownloadController::class, 'unapprove_file'])->name('unapprove-file-mass');

    // Approve dan Unappproval sarpras
    Route::put('/approve-sarpras/{Sarpras:id}', [SarprasController::class, 'approve_sarpras'])->name('approve-sarpras');
    Route::put('/approve-sarpras/aprrove', [SarprasController::class, 'approve_sarpras'])->name('approve-sarpras-mass');
    Route::put('/unapprove-sarpras/{Sarpras:id}', [SarprasController::class, 'unapprove_sarpras'])->name('unapprove-sarpras');
    Route::put('/unapprove-sarpras/unapprove', [SarprasController::class, 'unapprove_sarpras'])->name('unapprove-sarpras-mass');

    // Approve dan Unappproval Pejabat
    Route::put('/approve-pejabat/{HumanResource:id}', [HumanResourceController::class, 'approve_pejabat'])->name('approve-pejabat');
    Route::put('/approve-pejabat/aprrove', [HumanResourceController::class, 'approve_pejabat'])->name('approve-pejabat-mass');
    Route::put('/unapprove-pejabat/{HumanResource:id}', [HumanResourceController::class, 'unapprove_pejabat'])->name('unapprove-pejabat');
    Route::put('/unapprove-pejabat/unapprove', [HumanResourceController::class, 'unapprove_pejabat'])->name('unapprove-pejabat-mass');

    // Manajemen User
    Route::resource('/manajemen-user', UserController::class);
    Route::delete('/manajemen-user/delete', [UserController::class, 'destroy'])->name('delete-user-mass');

    // Jenis dan Jenjang

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UsersDataTable;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = User::get();

        if ($request->ajax()) {
            return DataTables::of($user)->addIndexColumn()
                ->addColumn('checkbox', function ($publication) {
                    return '<input type="checkbox" name="id" data-id="' . $publication->id . '">';
                })
                ->addColumn('action', function ($publication) {
                    if ($publication->id == "1") {
                        return '
                            <div class="btn-group">
                               
                            </div>
                            ';
                    } else {
                        return '
                        <div class="btn-group">
                            <a href="' . route('manajemen-user.edit', $publication->id) . '" class="btn btn-light m-1 h3 text-primary"><i class="fas fa-file-signature" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Edit"></i></a>
                        </div>
                        ';
                    }
                })
                ->addColumn('status', function ($publication) {
                    if ($publication->status == "0") {
                        return '<div class="badge bg-danger">Tidak Aktif</div>';
                    } else {
                        return '<div class="badge bg-success">Aktif</div>';
                    }
                })
                ->filter(function ($user) use ($request) {
                    if ($request->get('status') == '0' || $request->get('status') == '1') {
                        $user->where('status', $request->get('status'));
                    }
                    if (!empty($request->get('search'))) {
                        $user->where(function ($w) use ($request) {
                            $search = $request->get('search');
                            $w->orWhere('username', 'LIKE', "%$search%")
                                ->orWhere('name', 'LIKE', "%$search%")
                                ->orWhere('role', 'LIKE', "%$search%");
                        });
                    }
                })
                ->rawColumns(['checkbox', 'action', 'status'])->make(true);
        }

        return view('admin.dashboard.user.manajemen_user', [
            'total_user' => User::count(),
            'total_user_aktif' => User::where('status', 1)->count(),
            'total_user_tidak_aktif' => User::where('status', 0)->count(),
        ]);
    }


    public function changePassword()
    {
        return view('admin.dashboard.password.change_password');
    }

    public function updatePassword(Request $request)
    {
        # Validation
        $request->validate([
            'password_lama' => 'required|min:8|max:10',
            'password_baru' => 'required|min:8|max:10',
        ]);


        #Match The Old Password
        if (!Hash::check($request->password_lama, auth()->user()->password)) {
            return back()->with("error", "Password lama tidak cocok!");
        }


        #Update the new Password
        User::whereId(auth()->user()->id)->update([
            'password' => Hash::make($request->password_baru)
        ]);

        return redirect()->back()->with("success", "Password berhasil di update!");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data_user = User::all();
        return view('admin.dashboard.user.manajemen_user_add
        ', compact('data_user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validateData = $request->validate([
            'name' => 'required',
            'username' => 'required|min:3|max:50|unique:users,username',
            'role' => 'required',
            'password' => 'required|min:8|max:10',
            'status' => 'required'
        ]);

        // dd('Registrasi Berhasil');

        $validateData['password'] = bcrypt($validateData['password']);

        User::create($validateData);

        return redirect('/manajemen-user')->with('success', 'User berhasil di tambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data_user = User::find($id);
        return view('admin.dashboard.user.manajemen_user_form
        ', compact('data_user', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => 'required',
            'role' => 'required',
            'status' => 'required'
        ]);

        $user = User::find($id);

        $user->name = $request->name;
        $user->username = $request->username;
        $user->role = $request->role;
        $user->status = $request->status;
        $user->save();

        // $request->session()->flash();

        return redirect('/manajemen-user')->with('success', 'Update berhasil !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            if ($request->has('data')) {
                User::whereIn('id', $request->data)->delete();
                return response()->json([
                    'success' => true,
                    'message' => 'Data Berhasil Dihapus'
                ]);
            }
            $publication = User::find($id);
            $publication->delete();
            return response()->json([
                'success'   => true,
                'message'   => 'Berhasil Menghapus Data'
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ]);
        }
    }
}

resources/views/admin/dashboard/user/manajemen_user_add.blade.php
@extends('admin.main')

@section('content')
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header d-print-none">
            <div class="row align-items-center">
                <div class="col-auto">
                    <h2 class="page-title">
                        Tambah User
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row">
                <div class="col-md-8 mb-4 mb-md-0">
                    <form action="{{ route('manajemen-user.store') }}" method="POST">
                        @csrf
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="mb-3">
                                    <div class="form-label">Username</div>
                                    <input type="text" id="username" name="username"
                                        class="form-control @error('username') is-invalid @enderror"
                                        value="{{ old('username') }}">
                                    @error('username')
                                        <div class="invalid-feedback">
                                            Username sudah ada atau dapat di isikan terlebih dahulu!
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Nama</div>
                                    <input type="text" id="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}">
                                    @error('name')
                                        <div class="invalid-feedback">
                                            Nama dapat di isikan terlebih dahulu!
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Role</div>
                                    <select id="role" name="role"
                                        class="form-control @error('role') is-invalid @enderror">
                                        <option selected value="{{ old('role') }}">{{ old('role') }}</option>
                                        <option value="admin">Admin</option>
                                        <option value="operator">Operator</option>
                                    </select>
                                    @error('role')
                                        <div class="invalid-feedback">
                                            Role dapat di isikan terlebih dahulu!
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Status</div>
                                    <select name="status" id="" class="form-control">
                                        @if (old('status') == "1")
                                        <option selected value="{{ old('status') }}">Aktif</option>
                                        @elseif (old('status') == "0")
                                        <option selected value="{{ old('status') }}">Tidak Aktif</option>
                                        @else
                                        <option selected>Pilih Status</option>
                                        @endif
                                    
                                        <option value="1">Aktif</option>
                                        <option value="0">Tidak Aktif</option>
                                    </select>
                                    @error('status')
                                        <div class="invalid-feedback">
                                            Role dapat di isikan terlebih dahulu!
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Password</div>{{ old('password') }}
                                    <input type="text" id="password" name="password"
                                        class="form-control @error('password') is-invalid @enderror" value="{{ old('password') }}">
                                    @error('password')
                                        <div class="invalid-feedback">
                                            Password harus di isi dan minimal 8 karakter
                                        </div>
                                    @enderror
                                </div>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $(function() {
            $('#navbar-menu > .navbar-nav > .nav-item > .nav-link > .nav-link-title:contains("Manajemen User")')
                .parents('.nav-item').addClass('active');
        });
    </script>
@endsection

resources/views/admin/dashboard/user/manajemen_user_form.blade.php
@extends('admin.main')

@section('content')
    <div class="container-xl">
        <!-- Page title -->
        <div class="page-header d-print-none">
            <div class="row align-items-center">
                <div class="col-auto">
                    <h2 class="page-title">
                        Manajemen User
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row">
                <div class="col-md-8 mb-4 mb-md-0">
                    <form action="/manajemen-user/{{ $data_user->id }}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="mb-3">
                                    <div class="form-label">Username</div>
                                    <input type="text" id="username" name="username"
                                        class="form-control @error('username') is-invalid @enderror"
                                        value="{{ $data_user->username }}" >
                                    @error('username')
                                        <div class="invalid-feedback">
                                            Username dapat di isi terlebih dahulu
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Nama</div>
                                    <input type="text" id="name" name="name"
                                        class="form-control @error('name') is-invalid @enderror"
                                        value="{{ $data_user->name }}" >
                                    @error('name')
                                        <div class="invalid-feedback">
                                            Nama dapat di isi terlebih dahulu!
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Role</div>
                                    <select id="role" name="role" class="form-control @error('role') is-invalid @enderror">
                                        <option value="{{ $data_user->role }}" selected>{{ $data_user->role }}</option>
                                        <option value="admin">Admin</option>
                                        <option value="operator">Operator</option>
                                    </select>
                                    @error('role')
                                        <div class="invalid-feedback">
                                            Role dapat di isi terlebih dahulu!
                                        </div>
                                    @enderror
                                </div>
                                <div class="mb-3">
                                    <div class="form-label">Status</div>
                                    <select name="status" id="status" class="form-control @error('status') is-invalid @enderror">
                                        @if ($data_user->status == 0)
                                            <option value="{{ $data_user->status }}" selected >Tidak Aktif</option>
                                        @else
                                            <option value="{{ $data_user->status }}" selected >Aktif</option>
                                        @endif
                                        <option value="1">Aktif</option>
                                        <option value="0">Tidak Aktif</option>
                                    </select>
                                    @error('status')
                                        <div class="invalid-feedback">
                                            Status dapat di isi terlebih dahulu!
                                        </div>
                                    @enderror
                                </div>
                                <button type="submit" class="btn btn-primary">Simpan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $(function() {
            $('#navbar-menu > .navbar-nav > .nav-item > .nav-link > .nav-link-title:contains("Manajemen User")')
                .parents('.nav-item').addClass('active');
        });
    </script>
@endsection